---
name: Release
permissions: write-all
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.94.1'
          targets: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./target/wasm32-wasip1/release/miserly-link.wasm
